name: CI/CD using CML

on:
  push:
    branches: ["main"]

permissions:
  contents: write
  pull-requests: write
  issues: write
  checks: write
  statuses: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Setup CML
        uses: iterative/setup-cml@v2

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Train and Evaluate Model
        run: |
          python train.py

      - name: Verify Model Exists
        run: |
          ls -lh model.pkl

      - name: Generate Simple CML Report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # ← use built-in token
        run: |
          echo "# Student Risk Prediction Results" > report.md
          echo "## Model trained successfully ✅" >> report.md
          echo "![](./plots/results.png)" >> report.md
          cml comment create report.md

      - name: Build Docker Image
        run: |
          docker build -t student-risk-api .

      - name: Run Docker Container
        run: |
          docker run -d -p 8000:8000 student-risk-api